In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

In [ ]:
df = pd.read_csv('tweets_v2.csv', delimiter=',')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27915 entries, 0 to 27914
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  27915 non-null  int64 
 1   text        27913 non-null  object
 2   sentiment   27912 non-null  object
dtypes: int64(1), object(2)
memory usage: 654.4+ KB


In [ ]:
df.describe()

Unnamed: 0
count  27915.000000
mean   13957.000000
std     8058.510718
min        0.000000
25%     6978.500000
50%    13957.000000
75%    20935.500000
max    27914.000000

In [ ]:
df.head()

Unnamed: 0                                               text sentiment
0           0  • COPA DO BRASIL • FINAL (IDA)\n\n⚽ Corinthian...       neu
1           1  🥰 adorooo\n#VamosFlamengo \n#CORxFLA https://t...       neu
2           2  Boa Noite Nação Corintiana!\n#CORxFLA \n#Prime...       neu
3           3                           Fla x cor quem ganha em?       neu
4           4  Desfalques do #Flamengo contra o Corinthians: ...       neu

# Processamento dos textos

In [ ]:
def tweet_processing(tweets):
    import re
    from unidecode import unidecode
    import string
    from nltk.tokenize import word_tokenize
    
    # removendo URLs
    tweets['text_preproc'] = tweets['text'].apply(lambda x: re.sub(r"http\S+", "", str(x)))
    tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: re.sub('@[^\s]+','',str(x)))
    # transformando em minúsculo
    tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: x.lower())
    # removendo acentuação
    tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: unidecode(x))
    # removendo caracteres de nova linha
    tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: x.replace('\r\n',' '))
    
    tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: remove_stopwords(x))
    
    # removendo pontuação dos tweets
    tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)))
    # stemming
    tweets['text_preproc'] = tweets['text_preproc'].apply(lambda text: do_stem(text))
    
    # aplicando o tokenizer
    tweets['tokens'] = tweets['text_preproc'].apply(word_tokenize)
    return tweets

In [ ]:
import re

tweets = df.copy()
# removendo URLs
tweets['text_preproc'] = tweets['text'].apply(lambda x: re.sub(r"http\S+", "", str(x)))
tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: re.sub('@[^\s]+','',str(x)))
tweets.head()

Unnamed: 0                                               text sentiment  \
0           0  • COPA DO BRASIL • FINAL (IDA)\n\n⚽ Corinthian...       neu   
1           1  🥰 adorooo\n#VamosFlamengo \n#CORxFLA https://t...       neu   
2           2  Boa Noite Nação Corintiana!\n#CORxFLA \n#Prime...       neu   
3           3                           Fla x cor quem ganha em?       neu   
4           4  Desfalques do #Flamengo contra o Corinthians: ...       neu   

                                        text_preproc  
0  • COPA DO BRASIL • FINAL (IDA)\n\n⚽ Corinthian...  
1              🥰 adorooo\n#VamosFlamengo \n#CORxFLA   
2  Boa Noite Nação Corintiana!\n#CORxFLA \n#Prime...  
3                           Fla x cor quem ganha em?  
4  Desfalques do #Flamengo contra o Corinthians: ...

In [ ]:
from unidecode import unidecode

# transformando em minúsculo
tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: x.lower())
# removendo acentuação
tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: unidecode(x))
# removendo caracteres de nova linha
tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: x.replace('\r\n',' '))
tweets.head()

Unnamed: 0                                               text sentiment  \
0           0  • COPA DO BRASIL • FINAL (IDA)\n\n⚽ Corinthian...       neu   
1           1  🥰 adorooo\n#VamosFlamengo \n#CORxFLA https://t...       neu   
2           2  Boa Noite Nação Corintiana!\n#CORxFLA \n#Prime...       neu   
3           3                           Fla x cor quem ganha em?       neu   
4           4  Desfalques do #Flamengo contra o Corinthians: ...       neu   

                                        text_preproc  
0  * copa do brasil * final (ida)\n\n corinthians...  
1                adorooo\n#vamosflamengo \n#corxfla   
2  boa noite nacao corintiana!\n#corxfla \n#prime...  
3                           fla x cor quem ganha em?  
4  desfalques do #flamengo contra o corinthians: ...

In [ ]:
import nltk
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize

In [ ]:
def remove_stopwords(text):
    
    # separando o texto em uma lista
    words = text.split(' ')
    
    # coletando a lista de stopwords
    stop_words = set(stopwords.words('portuguese')) 

    # filtrando o texto, removendo as stopwords
    words_filtered = [w for w in words if w not in stop_words]
    
    # juntando a lista de palavras em texto novamente
    text_filtered = ' '.join(words_filtered)
    
    return text_filtered

In [ ]:
# removendo stopwords do nosso texto
tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: remove_stopwords(x))
tweets.head()

Unnamed: 0                                               text sentiment  \
0           0  • COPA DO BRASIL • FINAL (IDA)\n\n⚽ Corinthian...       neu   
1           1  🥰 adorooo\n#VamosFlamengo \n#CORxFLA https://t...       neu   
2           2  Boa Noite Nação Corintiana!\n#CORxFLA \n#Prime...       neu   
3           3                           Fla x cor quem ganha em?       neu   
4           4  Desfalques do #Flamengo contra o Corinthians: ...       neu   

                                        text_preproc  
0  * copa brasil * final (ida)\n\n corinthians x ...  
1                adorooo\n#vamosflamengo \n#corxfla   
2  boa noite nacao corintiana!\n#corxfla \n#prime...  
3                                fla x cor ganha em?  
4  desfalques #flamengo contra corinthians: bruno...

In [ ]:
import string

# removendo pontuação dos tweets
tweets['text_preproc'] = tweets['text_preproc'].apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)))

tweets.head()

Unnamed: 0                                               text sentiment  \
0           0  • COPA DO BRASIL • FINAL (IDA)\n\n⚽ Corinthian...       neu   
1           1  🥰 adorooo\n#VamosFlamengo \n#CORxFLA https://t...       neu   
2           2  Boa Noite Nação Corintiana!\n#CORxFLA \n#Prime...       neu   
3           3                           Fla x cor quem ganha em?       neu   
4           4  Desfalques do #Flamengo contra o Corinthians: ...       neu   

                                        text_preproc  
0   copa brasil  final ida\n\n corinthians x flam...  
1                  adorooo\nvamosflamengo \ncorxfla   
2  boa noite nacao corintiana\ncorxfla \nprimevid...  
3                                 fla x cor ganha em  
4  desfalques flamengo contra corinthians bruno h...

In [ ]:
# tweets['sentiment'] = '-'
# tweets.to_excel("tweets.xlsx")

In [ ]:
#  função para aplicar o stemming
def do_stem(text):
    
    # separando o texto em uma lista de palavras
    words = text.split(' ')
    
    stemmer = nltk.stem.RSLPStemmer()

    # aplicando o stemming no texto
    words_stem = [stemmer.stem(w) for w in words if len(w)>0]
    
    # juntando a lista de palavras em texto novamente
    text_stem = ' '.join(words_stem)
    
    return text_stem

In [ ]:
tweets['text_preproc'] = tweets['text_preproc'].apply(lambda text: do_stem(text))
tweets.head()

Unnamed: 0                                               text sentiment  \
0           0  • COPA DO BRASIL • FINAL (IDA)\n\n⚽ Corinthian...       neu   
1           1  🥰 adorooo\n#VamosFlamengo \n#CORxFLA https://t...       neu   
2           2  Boa Noite Nação Corintiana!\n#CORxFLA \n#Prime...       neu   
3           3                           Fla x cor quem ganha em?       neu   
4           4  Desfalques do #Flamengo contra o Corinthians: ...       neu   

                                        text_preproc  
0  cop brasil final ida\n\n corinth x flamengo\n ...  
1                     adorooo\nvamosflameng \ncorxfl  
2  boa noit naca corintiana\ncorxfl \nprimevide \...  
3                                  fla x cor ganh em  
4  desfalqu flameng contr corinth brun henriqu ro...

In [ ]:
from nltk.tokenize import word_tokenize

# aplicando o tokenizer
tweets['tokens'] = tweets['text_preproc'].apply(word_tokenize)
tweets.head()

Unnamed: 0                                               text sentiment  \
0           0  • COPA DO BRASIL • FINAL (IDA)\n\n⚽ Corinthian...       neu   
1           1  🥰 adorooo\n#VamosFlamengo \n#CORxFLA https://t...       neu   
2           2  Boa Noite Nação Corintiana!\n#CORxFLA \n#Prime...       neu   
3           3                           Fla x cor quem ganha em?       neu   
4           4  Desfalques do #Flamengo contra o Corinthians: ...       neu   

                                        text_preproc  \
0  cop brasil final ida\n\n corinth x flamengo\n ...   
1                     adorooo\nvamosflameng \ncorxfl   
2  boa noit naca corintiana\ncorxfl \nprimevide \...   
3                                  fla x cor ganh em   
4  desfalqu flameng contr corinth brun henriqu ro...   

                                              tokens  
0  [cop, brasil, final, ida, corinth, x, flamengo...  
1                    [adorooo, vamosflameng, corxfl]  
2  [boa, noit, naca, corintiana, corxfl, primevid...  
3                            [fla, x, cor, ganh, em]  
4  [desfalqu, flameng, contr, corinth, brun, henr...

# Separando os tweets base por sentimento

In [ ]:
def factorize_sentiment(sentiment):
    if sentiment == 'neg':
        return 0
    if sentiment == 'neu':
        return 1
    if sentiment == 'pos':
        return 2
    return -1

In [ ]:
tweets['sentiment_fact'] = tweets.sentiment.apply(lambda x : factorize_sentiment(x))

In [ ]:
tweets_pos = tweets[tweets.sentiment_fact == 2]
tweets_neg = tweets[tweets.sentiment_fact == 0]
tweets_neu = tweets[tweets.sentiment_fact == 1]
print(tweets_pos.shape)
print(tweets_neg.shape)
print(tweets_neu.shape)

(272, 6)
(396, 6)
(527, 6)


In [ ]:
from sklearn.model_selection import train_test_split

TRAIN_SIZE = 0.7
RANDOM_STATE = 42

X_pos = tweets_pos[['text_preproc', 'tokens']]
# X_pos = tweets_pos[['text_preproc']]
# X_pos = tweets_pos[['tokens']]
y_pos = tweets_pos[['sentiment_fact']]

X_neg = tweets_neg[['text_preproc', 'tokens']]
# X_neg = tweets_neg[['text_preproc']]
# X_neg = tweets_neg[['tokens']]
y_neg = tweets_neg[['sentiment_fact']]

X_neu = tweets_neu[['text_preproc', 'tokens']]
# X_neu = tweets_neu[['text_preproc']]
# X_neu = tweets_neu[['tokens']]
y_neu = tweets_neu[['sentiment_fact']]

X_pos_train, X_pos_test, y_pos_train, y_pos_test = train_test_split(X_pos, y_pos, train_size=TRAIN_SIZE, random_state=RANDOM_STATE)
X_neg_train, X_neg_test, y_neg_train, y_neg_test = train_test_split(X_neg, y_neg, train_size=TRAIN_SIZE, random_state=RANDOM_STATE)
X_neu_train, X_neu_test, y_neu_train, y_neu_test = train_test_split(X_neu, y_neu, train_size=TRAIN_SIZE, random_state=RANDOM_STATE)

# X_train = X_pos_train + X_neg_train + X_neu_train
X_train = pd.concat([X_pos_train, X_neg_train, X_neu_train],axis=0)
# X_test = X_pos_test + X_neg_test + X_neu_test
X_test = pd.concat([X_pos_test, X_neg_test, X_neu_test], axis=0)
# y_train = y_pos_train + y_neg_train + y_neu_train
y_train = pd.concat([y_pos_train, y_neg_train, y_neu_train],axis=0)
# y_test = y_pos_test + y_neg_test + y_neu_test
y_test = pd.concat([y_pos_test, y_neg_test, y_neu_test],axis=0)

print(X_train.shape)
print(X_test.shape)

(835, 2)
(360, 2)


# Representação numérica

## Bag of words 

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

BoW = CountVectorizer()

# treinando o modelo de vetorização e transformando os dados de treino
BoW_X_train = BoW.fit_transform(X_train['text_preproc']).toarray()

# aplicando o modelo treinado aos dados de teste
BoW_X_test  = BoW.transform(X_test['text_preproc']).toarray()

In [ ]:
print(BoW_X_test.shape)

(360, 3364)


In [ ]:
print(type(BoW))

<class 'sklearn.feature_extraction.text.CountVectorizer'>


In [ ]:
BoW_X_train.shape

(835, 3364)

In [ ]:
import pickle
pkl_filename="bow.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(BoW, file)

In [ ]:
import pickle
pkl_filename="doc_train.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(X_train['text_preproc'], file)

## Term Frequency - Inverse Document Frequency (TF-IDF)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

Tfidf = TfidfVectorizer()

# treinando o modelo de vetorização e transformando os dados de treino
Tfidf_X_train = Tfidf.fit_transform(X_train['text_preproc']).toarray()

# aplicando o modelo treinado aos dados teste
Tfidf_X_test  = Tfidf.transform(X_test['text_preproc']).toarray()

## Word Embedding

### Continuous Bag of words

In [ ]:
# from https://www.geeksforgeeks.org/python-word-embedding-using-word2vec
import gensim
from gensim.models import Word2Vec
# cbow_model = gensim.models.Word2Vec(X_test['text_preproc'], min_count = 1, vector_size = 50, window = 5)
cbow_model = gensim.models.Word2Vec(X_test['tokens'], min_count = 1, vector_size = 50, window = 10)
word2vec_cbow = cbow_model.wv

### Skip Gram

In [ ]:
# skipg_model = gensim.models.Word2Vec(X_test['text_preproc'], min_count = 1, vector_size = 50, window = 5, sg = 1)
skipg_model = gensim.models.Word2Vec(X_test['tokens'], min_count = 1, vector_size = 50, window = 10, sg = 1)
word2vec_skipg = skipg_model.wv

In [ ]:
def get_average_word2vec(tokens_list, vector, generate_missing=False, k=50):
    if len(tokens_list)<1:
        return np.zeros(k)
    if generate_missing:
        vectorized = [vector[word] if word in vector else np.random.rand(k) for word in tokens_list]
    else:
        vectorized = [vector[word] if word in vector else np.zeros(k) for word in tokens_list]
    length = len(vectorized)
    summed = np.sum(vectorized, axis=0)
    averaged = np.divide(summed, length)
    return averaged

def get_word2vec_embeddings(vectors, clean_questions, generate_missing=False):
    embeddings = clean_questions['tokens'].apply(lambda x: get_average_word2vec(x, vectors, 
                                                                                generate_missing=generate_missing))
    return list(embeddings)

In [ ]:
word2vec_cbow_X_train = get_word2vec_embeddings(word2vec_cbow, X_train)
word2vec_cbow_X_test = get_word2vec_embeddings(word2vec_cbow, X_test)

word2vec_skipg_X_train = get_word2vec_embeddings(word2vec_skipg, X_train)
word2vec_skipg_X_test = get_word2vec_embeddings(word2vec_skipg, X_test)

# Testando modelos

## NaiveBayes e BoW

In [ ]:
# importando as bibliotecas
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

# criando e treinando o modelo
naive_bayes_classifier = MultinomialNB(alpha=1)
naive_bayes_classifier.fit(BoW_X_train, y_train)

# realizando a predição nos dados de teste
y_pred = naive_bayes_classifier.predict(BoW_X_test)

# finalmente, vamos ver os resultados do modelo
score1 = metrics.accuracy_score(y_test, y_pred)
print(score1)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

0.6638888888888889
[[ 87  18  14]
 [ 28 111  20]
 [ 20  21  41]]
              precision    recall  f1-score   support

           0       0.64      0.73      0.69       119
           1       0.74      0.70      0.72       159
           2       0.55      0.50      0.52        82

    accuracy                           0.66       360
   macro avg       0.64      0.64      0.64       360
weighted avg       0.66      0.66      0.66       360



C:\Users\andre\anaconda3\envs\datascience\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# naive_bayes_classifier.predict_proba(y_pred).round(3)

## NaiveBayes e TF-IDF

In [ ]:
from sklearn.naive_bayes import MultinomialNB

naive_bayes_classifier = MultinomialNB(alpha=2)
naive_bayes_classifier.fit(Tfidf_X_train, y_train)
y_pred = naive_bayes_classifier.predict(Tfidf_X_test)

score1 = metrics.accuracy_score(y_test, y_pred)
print(score1)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

0.6083333333333333
[[ 70  48   1]
 [ 15 144   0]
 [ 14  63   5]]
              precision    recall  f1-score   support

           0       0.71      0.59      0.64       119
           1       0.56      0.91      0.70       159
           2       0.83      0.06      0.11        82

    accuracy                           0.61       360
   macro avg       0.70      0.52      0.48       360
weighted avg       0.67      0.61      0.55       360



C:\Users\andre\anaconda3\envs\datascience\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## SVC e BoW

In [ ]:
from sklearn.svm import SVC

svc_bow_classifier = SVC(kernel="poly")
svc_bow_classifier.fit(BoW_X_train, y_train)
y_pred = svc_bow_classifier.predict(BoW_X_test)

score1 = metrics.accuracy_score(y_test, y_pred)
print(score1)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

C:\Users\andre\anaconda3\envs\datascience\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.46944444444444444
[[ 10 109   0]
 [  1 158   0]
 [  0  81   1]]
              precision    recall  f1-score   support

           0       0.91      0.08      0.15       119
           1       0.45      0.99      0.62       159
           2       1.00      0.01      0.02        82

    accuracy                           0.47       360
   macro avg       0.79      0.36      0.27       360
weighted avg       0.73      0.47      0.33       360



## SVC E TFIDF

In [ ]:
from sklearn.svm import SVC

svc_classifier = SVC(kernel="sigmoid")
svc_classifier.fit(Tfidf_X_train, y_train)
y_pred = svc_classifier.predict(Tfidf_X_test)

score1 = metrics.accuracy_score(y_test, y_pred)
print(score1)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

C:\Users\andre\anaconda3\envs\datascience\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7027777777777777
[[ 91  22   6]
 [ 17 130  12]
 [ 17  33  32]]
              precision    recall  f1-score   support

           0       0.73      0.76      0.75       119
           1       0.70      0.82      0.76       159
           2       0.64      0.39      0.48        82

    accuracy                           0.70       360
   macro avg       0.69      0.66      0.66       360
weighted avg       0.70      0.70      0.69       360



In [ ]:
# import pickle

# with open("svc_tfidf_sig.pkl", 'wb') as file:
#     pickle.dump(svc_classifier, file)
# with open("tfidf.pkl", 'wb') as file:
#     pickle.dump(Tfidf, file)
# with open("tfidf_train.pkl", 'wb') as file:
#     pickle.dump(X_train['text_preproc'], file)

## SVC e Word2Vec CBoW

In [ ]:
from sklearn.svm import SVC

svc_classifier = SVC(kernel="rbf")
svc_classifier.fit(word2vec_cbow_X_train, y_train)
y_pred = svc_classifier.predict(word2vec_cbow_X_test)

score1 = metrics.accuracy_score(y_test, y_pred)
print(score1)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

0.5916666666666667
[[ 76  35   8]
 [ 29 125   5]
 [ 24  46  12]]
              precision    recall  f1-score   support

           0       0.59      0.64      0.61       119
           1       0.61      0.79      0.68       159
           2       0.48      0.15      0.22        82

    accuracy                           0.59       360
   macro avg       0.56      0.52      0.51       360
weighted avg       0.57      0.59      0.56       360



C:\Users\andre\anaconda3\envs\datascience\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## SVC e Word2Vec Skip Gram

In [ ]:
from sklearn.svm import SVC

svc_classifier = SVC()
svc_classifier.fit(word2vec_skipg_X_train, y_train)
y_pred = svc_classifier.predict(word2vec_skipg_X_test)

score1 = metrics.accuracy_score(y_test, y_pred)
print(score1)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

0.44166666666666665
[[  0 119   0]
 [  0 159   0]
 [  0  82   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       119
           1       0.44      1.00      0.61       159
           2       0.00      0.00      0.00        82

    accuracy                           0.44       360
   macro avg       0.15      0.33      0.20       360
weighted avg       0.20      0.44      0.27       360



C:\Users\andre\anaconda3\envs\datascience\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\andre\anaconda3\envs\datascience\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\andre\anaconda3\envs\datascience\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\andre\anaconda3\envs\datascience\lib\site-pa